CREATE DATABASE TCC;
USE TCC;
CREATE TABLE USUARIOS (
  ID_USUARIO int(11) PRIMARY KEY AUTO_INCREMENT,
  NOME_PR varchar(80),
  NOME_SE varchar(80),
  EMAIL varchar(80) UNIQUE,
  SENHA varchar(255)
);
CREATE TABLE EXERCICIOS (
ID_EXERCICIOS INT PRIMARY KEY AUTO_INCREMENT,
ID_USUARIO INT,
NOME VARCHAR(80),
DESCRICAO TEXT,
TIPO ENUM("TEMPO","REPETICAO"),
TEMPO_SEGUNDOS INT,
QUANT_REPETICAO INT,
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO) 
);